FROM 192.168.1.1/dev5/java:8
MAINTAINER admin@gmail.com

RUN mkdir /apps
ADD ./target/*.jar /apps/app.jar
RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo "Asia/Shanghai" > /etc/timezone

CMD ["java","-jar","/apps/app.jar","--spring.profiles.active-dat","-Xms4094M","-Xmx4096M"]
